#!/usr/bin/env python3
"""Regenerates the data half of `src/sprites.rs` from `maps.py`.

    python3 scripts/pixel-art/gen_rust.py && cargo fmt

Every map is rendered with `render.py` and baked into one shared palette.
Everything below the "building textures" marker in sprites.rs is
hand-written and kept as is.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from maps import A, check
from render import GRID, render

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(REPO, "src", "sprites.rs")
MARKER = "// --- building textures "
EYE_CODE = '*'
CODES = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz#$%&+-=?@^~"


def main():
    check()
    rendered = {name: render(name, rows, pal) for name, (rows, pal) in sorted(A.items())}
    colours = sorted({c for px, _ in rendered.values() for row in px for c in row if c})
    assert len(colours) < len(CODES), f"{len(colours)} colours, only {len(CODES)} codes"
    code = {c: CODES[i] for i, c in enumerate(colours)}
    eye = (16, 20, 32)

    out = [
        "//! Pixel art. The sprite data (above the \"building textures\" marker) is",
        "//! generated by `scripts/pixel-art/gen_rust.py` from `maps.py`: edit the",
        "//! maps and rerun, never the data. The code below the marker is hand-written.",
        "",
        "use macroquad::prelude::*;",
        "",
        "use crate::nodule::Morph;",
        "use crate::tree::{Group, Phylogeny};",
        "",
        f"pub const GRID: usize = {GRID};",
        "",
        "/// One character per pixel: `.` transparent, `*` an eye, anything else",
        "/// indexes `PALETTE` through `CODES`.",
        "type SpriteDef = [&'static str; GRID];",
        "",
        f"const CODES: &str = \"{''.join(code[c] for c in colours)}\";",
        "",
        "#[rustfmt::skip]",
        f"const PALETTE: [u32; {len(colours)}] = [",
    ]
    for i in range(0, len(colours), 8):
        out.append("    " + " ".join(f"0x{r:02X}{g:02X}{b:02X}," for r, g, b in colours[i:i + 8]))
    out += [
        "];",
        "",
        f"const EYE: u32 = 0x{eye[0]:02X}{eye[1]:02X}{eye[2]:02X};",
        "",
        "/// Keyed by `Taxon::name`; \"Ancestor\" is the root's glyph.",
        "#[rustfmt::skip]",
        "fn animal_def(name: &str) -> Option<SpriteDef> {",
        "    Some(match name {",
    ]
    for name, (px, eyes) in rendered.items():
        out.append(f'        "{name}" => [')
        for y in range(GRID):
            row = "".join(
                EYE_CODE if (x, y) in eyes else code[px[y][x]] if px[y][x] else "."
                for x in range(GRID))
            out.append(f'            "{row}",')
        out.append("        ],")
    out += ["        _ => return None,", "    })", "}", "", ""]

    old = open(OUT).read()
    tail = old[old.index(MARKER):]
    open(OUT, "w").write("\n".join(out) + tail)
    print(f"wrote {len(rendered)} sprites, {len(colours)} colours to {OUT}")


if __name__ == "__main__":
    main()
