"""Every sprite as a 16x16 material map, keyed by `Taxon::name`.

Letters: `.` empty, `b` body, `l` belly or pale part, `d` dark marking,
`f` limbs or fins, `r`/`g` accents, all coloured by the map's own dict and
shaded by `render.py`; `e` eye white, `k` eye, `w` glint, `t` ivory and `m`
mouth have fixed colours. "Ancestor" is the root's glyph.

Style rules: vertebrates in side profile facing right, flat animals from
above, round ones from the front, and one signature feature exaggerated.
"""

from render import GRID
from palette import FIXED


def mirror(half):
    return [h + h[::-1] for h in half]


A = {}

A["Jellyfish"] = (mirror([
    "........",
    "........",
    ".....bbb",
    "...bbbll",
    "..bbblll",
    "..bbllgl",
    ".bbbllll",
    ".bbbbbbb",
    ".fbfbfbf",
    "..f.f.rr",
    "..f.f.r.",
    ".f..f.rr",
    ".f.f...r",
    "..f.f.r.",
    "..f..f..",
    "........",
]), dict(b=0xC47BE0, l=0xF0B8FF, f=0x9C6AD8, r=0xFF8FC8, g=0xFFFFFF))

A["Octopus"] = (mirror([
    "........",
    "......bb",
    "....bbbb",
    "...bbbbb",
    "...bbdbb",
    "...bbbbb",
    "...bbbbb",
    "...bwkbb",
    "...bkkbb",
    "..bbbbbb",
    ".bbbbbbb",
    "bb.bb.bb",
    "b.bb.bb.",
    "bl.b.bl.",
    ".bb..b..",
    "........",
]), dict(b=0xE0664A, l=0xFFB39A, d=0xA8402E))

A["Snail"] = ([
    "................",
    "................",
    "................",
    "................",
    "................",
    "....dddd........",
    "...dbbbbd.......",
    "..dbbddbbd...k.k",
    "..dbdbbdbd...l.l",
    "..dbdbddbd...l.l",
    "..dbbddbbd..lll.",
    "...dbbbbd..llll.",
    ".lllddddlllllll.",
    "lllllllllllllll.",
    "................",
    "................",
], dict(b=0xD8A860, d=0x8A5A30, l=0xB8B0A0))

A["Crab"] = (mirror([
    "........",
    "........",
    ".bb.....",
    "b..b....",
    "b.bb....",
    "bbb...k.",
    ".bb...b.",
    "..b.bbbb",
    "..bbbbbb",
    "...bbbbb",
    "..fbbbbb",
    ".f.fbbll",
    "f.f.f.ff",
    "..f.f...",
    "........",
    "........",
]), dict(b=0xE0664A, l=0xFFB39A, f=0xB84A34))

A["Beetle"] = (mirror([
    "....f...",
    ".....f..",
    "......bb",
    "......eb",
    ".....ddd",
    "..f.dddd",
    "...fdddd",
    "...bbbbd",
    ".f.bbbbd",
    "f.bbbbbd",
    "..bbbbld",
    ".fbbbbld",
    "f..bbbbd",
    "...bbbbd",
    ".....bbd",
    "........",
]), dict(b=0x4F8A3A, l=0x9FE0A0, d=0x2A4A2A, f=0x2A2A30, e=0xFFD86B))

A["Butterfly"] = (mirror([
    "........",
    ".....f..",
    "......f.",
    ".bbb...d",
    "brrbb..d",
    "brrrbb.d",
    "bbrrbbbd",
    ".bbbbbbd",
    "..bbbbbd",
    ".bbllbbd",
    "bbllbb.d",
    "bbbbb..d",
    ".bbb....",
    "........",
    "........",
    "........",
]), dict(b=0xFFA340, r=0x2A2A30, l=0xFFE0A0, d=0x3A2A20, f=0x3A2A20))

A["Starfish"] = (mirror([
    "........",
    ".......b",
    "......bb",
    "......bd",
    "......bb",
    "bbbbbbbd",
    ".bbdbbbb",
    "..bbbbdb",
    "...bdbbb",
    "...bbbbb",
    "..bbd.bb",
    "..bb...b",
    ".bb.....",
    ".b......",
    "........",
    "........",
]), dict(b=0xFF8A50, d=0xB84A34))

A["Trilobite"] = (mirror([
    "........",
    "........",
    "....bbbb",
    "..bbbbbl",
    ".bbkbbbl",
    "bbbbbbll",
    "b.dddddd",
    "b.bbbdbl",
    "b.dddddd",
    "...bbdbl",
    "...ddddd",
    "....bdbl",
    "....dddd",
    ".....bbl",
    "......bb",
    "........",
]), dict(b=0x8A7A6A, l=0xC8B8A0, d=0x4A3E36))

A["Shark"] = ([
    "................",
    "................",
    "................",
    "................",
    ".........b......",
    "b.......bb......",
    "bb.....bbb......",
    ".bb.bbbbbbbbbb..",
    "..bbbbbbbbbbbkb.",
    "..bbbbbbbbdbdbbb",
    "..blllllllldldll",
    ".bb.lllllllllll.",
    "bb.....ff..f....",
    "b.......f.......",
    "................",
    "................",
], dict(b=0x6F8FA8, l=0xDDE6EE, d=0x3C5468, f=0x5A7A94))

A["Frog"] = ([
    "................",
    "................",
    "................",
    "................",
    "...........bb...",
    "..........bwkb..",
    "........bbbbbbb.",
    "......bbbbbbbbbb",
    "....bbdbbbbbbbbb",
    "...bbbbbbbbmmmmm",
    "..bbbbdbbbllllll",
    "..bbbbbbbllllll.",
    ".bbbbbbbblfll...",
    ".ffbbbbffbf.....",
    "ffff.ffff.ff....",
    "................",
], dict(b=0x5CB84A, l=0xCEAA6E, d=0x2E6A2A, f=0x4A9A3C))

A["Turtle"] = ([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "....dddddd......",
    "...dbbdbbbd.....",
    "..dbbbdbbbbd....",
    ".dbdbbdbbdbbd.ll",
    ".dbbdbbbdbbbdlkl",
    ".ddddddddddddlll",
    "..lll.....lll.l.",
    "..ll......ll....",
    "................",
    "................",
], dict(b=0x7A8A3A, d=0x4A5A28, l=0x9AB070))

A["Crocodile"] = ([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "............bk..",
    "...d.d.d.d.bbbb.",
    "bbbbbbbbbbbbbbbb",
    ".bbbbbbbbbbbbbbb",
    "...llllllllltbtb",
    "...f.f...f.f....",
    "..ff.f..ff.f....",
    "................",
], dict(b=0x5A7A3A, d=0x33472A, l=0xA8A870, f=0x46602E))

A["T. rex"] = ([
    "..........bbbb..",
    ".........bbkbbbb",
    ".........bbbbbbb",
    ".........bbbmmmm",
    ".........bbbtttt",
    "........bbbbbb..",
    ".......bbbbb.f..",
    "......bbbbbbf...",
    "b....bbbbbbb....",
    "bb..bbbbbbll....",
    ".bbbbbbbbbll....",
    "..bbbbbbbll.....",
    "....bbb.bb......",
    "....bb...b......",
    "...bbb..bbb.....",
    "................",
], dict(b=0x6A8A4A, l=0xB8B070, f=0x4A6A34))

A["Bird"] = ([
    "................",
    "................",
    "................",
    "................",
    "........bbb.....",
    ".......bbkbr....",
    ".......bbbbrr...",
    "......bbbbb.....",
    "....bbbbbll.....",
    "..bbbbbblll.....",
    "bbbddbbllll.....",
    "..bbddbbll......",
    "......f.f.......",
    "......f.f.......",
    ".....ff.ff......",
    "................",
], dict(b=0x5A8AC8, l=0xE8C070, d=0x2E4A7A, r=0xFFB040, f=0x3A3A40))

A["Elephant"] = ([
    "................",
    "................",
    "................",
    "......bbbbb.....",
    "....bbbbbbbbb...",
    "..bbbbbbbbddbb..",
    ".bbbbbbbbdddbkb.",
    ".bbbbbbbbdddbbbb",
    "bbbbbbbbbdddbbbb",
    "bbbbbbbbbbddbtbb",
    ".bbbbbbbbbbbt.bb",
    ".bbb.bbb.bbb..bb",
    ".bbb.bbb.bbb..bb",
    ".bbb.bbb.bbb..b.",
    ".ddd.ddd.ddd....",
    "................",
], dict(b=0x8A8F9C, d=0x55596A))

A["Mammoth"] = ([
    "................",
    "................",
    ".....bbbb.......",
    "...bbbbbbbb.....",
    "..bbbbbbbbbbb...",
    ".bbdbbdbbbbbbb..",
    "bbbbbbbbbbdbkbb.",
    "bdbbdbbdbbdbbbb.",
    "bbbbbbbbbbdbbbbt",
    "bdbbdbbdbbbdb.bt",
    ".bbbbbbbbbbb..tt",
    ".bdb.bdb.bdb.tt.",
    ".bbb.bbb.bbb.b..",
    ".bdb.bdb.bdb....",
    ".ddd.ddd.ddd....",
    "................",
], dict(b=0x8A5A3A, d=0x4A2E1E))

A["Whale"] = ([
    "................",
    "................",
    "................",
    "............g.g.",
    ".............g..",
    ".............g..",
    "b.....bbbbbbbb..",
    "bb..bbbbbbbbbbbb",
    ".bbbbbbbbbbbbbbb",
    ".bbbbbbbbbbbkbbb",
    "b.bbllllllllllbb",
    "bb..lldldldldll.",
    ".......lllll....",
    ".........f......",
    "................",
    "................",
], dict(b=0x3C5A7A, l=0xB8C8D8, d=0x6A8098, f=0x2E4A66, g=0xDDF0FF))

A["Wolf"] = ([
    "................",
    "................",
    "...........b.b..",
    "..........bbbb..",
    "..........bbbkb.",
    "..........bbbbbb",
    "..........bbbbkk",
    "b.....bbbbbbll..",
    "bbbbbbbbbbbbl...",
    ".bbbbbbbbbbbl...",
    "..bbbbbbbbbbl...",
    "..bbllllllbbl...",
    "..bb.....bb.b...",
    "..b.b....b..b...",
    ".bb.bb..bb.bb...",
    "................",
], dict(b=0x8A8F9C, l=0xD8D8DE, d=0x55596A))

A["Human"] = (mirror([
    "........",
    "......dd",
    ".....ddd",
    ".....ddd",
    ".....bkb",
    "......bb",
    "....bbbb",
    "...b.bbb",
    "...b.bbb",
    "...b.bbb",
    ".....rrr",
    ".....bb.",
    ".....bb.",
    ".....bb.",
    "....bbb.",
    "........",
]), dict(b=0xC8906E, d=0x4A2E20, r=0x6A4A30))

A["Ancestor"] = (mirror([
    "........",
    "....f...",
    ".....f..",
    "...bbb..",
    "..bblbb.",
    "..bbbbb.",
    "f..bbb.b",
    ".f....bb",
    "..bbb.bl",
    ".bblbb.b",
    ".bbbbb..",
    "..bbb...",
    "....f...",
    ".....f..",
    "........",
    "........",
]), dict(b=0x5FC0B0, l=0xDFFFF8, f=0x9FE8E0))

A["Sea Sponge"] = ([
    "................",
    ".....bbb........",
    "....bdddb.......",
    "....bbbbb..bbb..",
    "....bdbbb.bdddb.",
    "....bbbdb.bbbbb.",
    ".bb.bbbbb.bdbbb.",
    "bddbbdbbb.bbbdb.",
    "bbbbbbbdb.bbbbb.",
    "bdbbbbbbb.bdbbb.",
    "bbbdbbdbbbbbbbb.",
    "bbbbbbbbbbbbdbb.",
    ".bbbbbbbbbbbbb..",
    "..llllllllllll..",
    "................",
    "................",
], dict(b=0xD8A860, d=0x8A5A30, l=0x6A6070))

A["Comb Jelly"] = (mirror([
    "........",
    "......bb",
    ".....bbl",
    "....bgll",
    "...bglrl",
    "...bllgl",
    "..bgllrl",
    "..bllrgl",
    "..bgllgl",
    "..bllrll",
    "...bgllg",
    "...bllrl",
    "....bgll",
    ".....bbl",
    "......f.",
    ".....f..",
]), dict(b=0x8FD8D0, l=0xCFF5F0, g=0xFFB0E0, r=0x80C0FF, f=0x8FD8D0))

A["Placozoan"] = ([
    "................",
    "................",
    "................",
    "................",
    "......bbbb......",
    "...bbbbbbbbb....",
    "..bbllbbbdbbbb..",
    ".bbllbbbbbbbbbb.",
    ".bbbbbdbbbllbbbb",
    "bbbbbbbbbbllbbb.",
    ".bbdbbbbbbbbdbb.",
    "..bbbbbllbbbbb..",
    "...bbbbbbbbb....",
    ".....bbb..bb....",
    "................",
    "................",
], dict(b=0xE8A0B0, l=0xF8D0D8, d=0xA86070))

A["Coral"] = ([
    "................",
    "..b.....b...b...",
    "..b..b..b..bb...",
    "..bb.b.bb..b..b.",
    "...b.bbb..bb.bb.",
    ".b.bb.b..bb..b..",
    ".bb.bbb.bb..bb..",
    "..bb.bbbb..bb...",
    "...bb.bbbbbb....",
    "....bbbbbb......",
    ".....bbbb.......",
    "......bb........",
    "......bb........",
    "....dddddd......",
    "..dddddddddd....",
    "................",
], dict(b=0xE0806A, d=0x5A5260))

A["Acoel Worm"] = ([
    "................",
    "................",
    "................",
    "................",
    "................",
    "...........bb...",
    "..........bllb..",
    ".........bllkb..",
    "........bllbb...",
    "......bbllb.....",
    "....bbllbb......",
    "..bbllbb........",
    ".bllbb..........",
    ".bbb............",
    "................",
    "................",
], dict(b=0xCDA37C, l=0xE8C8A0))

A["Flatworm"] = ([
    "................",
    "................",
    "................",
    "................",
    "................",
    "............b...",
    "..........bbbb..",
    "...bbbbbbbbbekb.",
    ".bbllllllllbbbbb",
    "...bbbbbbbbbekb.",
    "..........bbbb..",
    "............b...",
    "................",
    "................",
    "................",
    "................",
], dict(b=0xB08060, l=0xD0A880))

A["Segmented Worm"] = ([
    "................",
    "................",
    "................",
    "................",
    "................",
    "..........f.f...",
    "....f.f.f.bbbb..",
    "...bbbbbbbbdbkb.",
    "..bdbdbdbdbbbbbb",
    ".bbbbbbbbbb.f.f.",
    "bb.f.f.f.f......",
    "b...............",
    "................",
    "................",
    "................",
    "................",
], dict(b=0xC86A5A, d=0x8A3E3A, f=0xE8A080))

A["Nematode"] = ([
    "................",
    "................",
    "...........bb...",
    "..........bllb..",
    ".........bl..bb.",
    ".........bl.....",
    "..........bl....",
    "...........bl...",
    "............bl..",
    "............bl..",
    "...........bl...",
    "..bb......bl....",
    ".b..bb..bbl.....",
    "......bbll......",
    "................",
    "................",
], dict(b=0xD8C8B8, l=0xF0E8E0))

A["Clam"] = (mirror([
    "........",
    "........",
    "........",
    "......bb",
    "....bbbb",
    "...bbdbd",
    "..bbdbdb",
    ".bbdbdbd",
    ".bdbdbdb",
    "bbdbdbdb",
    "bdbdbdbd",
    ".dbdbdbd",
    "..ddbbbb",
    "....bbbb",
    "...bbbbb",
    "........",
]), dict(b=0xE8B090, d=0xB07A5A))

A["Squid"] = (mirror([
    ".......b",
    "......bb",
    "....bbbb",
    "..bbbbbb",
    "....bbbb",
    ".....bbb",
    ".....bbb",
    ".....bbb",
    ".....bbb",
    "....kbbb",
    ".....bbb",
    "....b.bb",
    "...b.b.b",
    "...b.b.b",
    "..b..b.b",
    "..b.....",
]), dict(b=0xE89080))

A["Ammonite"] = ([
    "................",
    "................",
    "....dddddd......",
    "...dbbbbbbd.....",
    "..dbbddddbbd....",
    ".dbbdbbbbdbbd...",
    ".dbdbbddbbdbd...",
    ".dbdbdbbdbdbd...",
    ".dbdbbdbbdbbd...",
    ".dbbdbbbdbbbdll.",
    "..dbbddddbbdlkl.",
    "...dbbbbbbdllll.",
    "....ddddddf.f.f.",
    "..........f.f..f",
    "................",
    "................",
], dict(b=0xD8B890, d=0x8A6A48, l=0xC89080, f=0xC89080))

A["Earthworm"] = ([
    "................",
    "................",
    "................",
    "................",
    "......bbbb......",
    ".....bdbbdb.....",
    "....bb....bb....",
    "....bd....db....",
    "...bb......bb...",
    "...bd......db...",
    "..rrr......bb...",
    "..bb........bb..",
    "ffffffffffffffff",
    ".ffffffffffffff.",
    "................",
    "................",
], dict(b=0xE8A0A0, d=0xB86A70, r=0xC05A70, f=0x6A4A30))

A["Horseshoe Crab"] = (mirror([
    "........",
    ".....bbb",
    "...bbbbb",
    "..bbbbbd",
    ".kbbbbbd",
    "bbbbbbbd",
    "bbbbbbbd",
    "bbbbbbbd",
    ".b.ddddd",
    "...bbbbd",
    "..b.bbbd",
    "....bbbd",
    "...b.bbb",
    ".......b",
    ".......b",
    ".......b",
]), dict(b=0x9A7A50, d=0x5A4A30))

A["Scorpion"] = ([
    "................",
    "................",
    ".....bbbb.......",
    "....b....bt.....",
    "...b............",
    "..bb............",
    "..b.............",
    "..bb.......b.bb.",
    "...bbbbbbbbbbbb.",
    "...bbbbbbbbbkbbb",
    "....fbfbfbfbb.bb",
    "...f.f.f.f......",
    "..f.f.f.f.......",
    "................",
    "................",
    "................",
], dict(b=0x5A4A38, f=0x3A3028))

A["Spider"] = (mirror([
    "........",
    "..ff....",
    ".f..f...",
    "f....f..",
    "f..ff.bb",
    "..f..fbk",
    ".f.ff.bb",
    "f.f..fbb",
    "..f.f.dd",
    ".f..bbbb",
    "f..bbbbb",
    "...bbdbb",
    "...bbbbd",
    "....bbbb",
    ".....bbb",
    "........",
]), dict(b=0x3A3038, d=0xE08040, f=0x3A3038))

A["Dragonfly"] = (mirror([
    "........",
    "......rr",
    "......rb",
    ".gggg.bb",
    "ggggggbb",
    ".ggggggb",
    "..gggg.b",
    ".ggggg.b",
    "gggggg.b",
    ".gggg..b",
    ".......b",
    ".......b",
    ".......b",
    ".......b",
    ".......d",
    "........",
]), dict(b=0x4A90C0, g=0xCFEFF0, r=0x60B060, d=0x2E4A7A))

A["Ant"] = ([
    "................",
    "................",
    "................",
    "................",
    "............f.f.",
    "...........f.f..",
    "..bbbb.....bbb..",
    ".bbbbbb...bbbbb.",
    ".bbbbbbb.b.bbkbb",
    ".bbbbbb.bbb.bbb.",
    "..bbbb.f.f.f.b..",
    "...f..f..f..f...",
    "..f..f...f...f..",
    ".f..f....f....f.",
    "................",
    "................",
], dict(b=0xA84A30, f=0x6A2A20))

A["Tardigrade"] = ([
    "................",
    "................",
    "................",
    "................",
    "................",
    "....bbbbbbbb....",
    "..bbldbldbldbb..",
    ".bbbdbbdbbdbbbb.",
    "bbbbdbbdbbdbbkbb",
    "bbbbdbbdbbdbbbbb",
    ".bbbbbbbbbbbbbm.",
    "..fbb.fbb.fbb.f.",
    "..ff..ff..ff..ff",
    "..tt..tt..tt..tt",
    "................",
    "................",
], dict(b=0xC8B8A0, l=0xE8DCC8, d=0x9A8A70, f=0xB0A088))

A["Anomalocaris"] = (mirror([
    "..f.....",
    ".f.f....",
    ".f..f...",
    "..f..fbb",
    "...k.bbb",
    "....bbbb",
    "..ddbbbl",
    ".dddbbbl",
    "..ddbbbl",
    ".dddbbbl",
    "..ddbbbl",
    "...dbbbl",
    "....bbbl",
    ".....bbb",
    "...dd.bb",
    "..dd....",
]), dict(b=0xC87050, d=0x8A4A3A, f=0xE0906A, l=0xE0A080))

A["Centipede"] = ([
    "................",
    "................",
    "................",
    "................",
    "................",
    "...........f..f.",
    ".f.f.f.f.f.f.ff.",
    "bdbdbdbdbdbdbbbb",
    "bbbbbbbbbbbbbbkb",
    ".f.f.f.f.f.f.f..",
    "f.f.f.f.f.f.f...",
    "................",
    "................",
    "................",
    "................",
    "................",
], dict(b=0xB05A30, d=0x6A3020, f=0xD08040))

A["Shrimp"] = ([
    "................",
    "................",
    "..............ff",
    "............ff..",
    "......bbbbbbbf..",
    "....bbdbbdbbkbf.",
    "...bbbbbbbbbbbb.",
    "..bbbbbbbbbbbll.",
    ".bbb....f.f.f...",
    ".bb.............",
    "bbb.............",
    "bb.b............",
    "................",
    "................",
    "................",
    "................",
], dict(b=0xF08070, d=0xC05A50, l=0xF8B0A0, f=0xE07060))

A["Bee"] = ([
    "................",
    "................",
    "................",
    "......gggg......",
    ".....g....g.gg..",
    "......gggg.g..g.",
    "....brbrb.ggg...",
    "...brbrbrbbb.f..",
    "..rbrbrbrbbbbkf.",
    "..brbrbrbrbbbb..",
    "...brbrbr.ff....",
    "..t.f.f.f.......",
    "................",
    "................",
    "................",
    "................",
], dict(b=0xFFC040, r=0x2A2A30, g=0xDFF0F8, f=0x2A2A30))

A["Meganeura"] = (mirror([
    "........",
    "......rr",
    "......bb",
    "gggggg.b",
    "gdgdggbb",
    "gggdgg.b",
    ".ggggg.b",
    "gggggg.b",
    "gdgdgg.b",
    ".gggg..b",
    ".......b",
    ".......b",
    ".......b",
    ".......b",
    ".......b",
    ".......d",
]), dict(g=0xC8A870, d=0x6A4A30, b=0x4A6A3A, r=0x80A040))

A["Sea Urchin"] = (mirror([
    "....f...",
    ".f...f.f",
    "..f..f.f",
    "f..fbbbb",
    ".ffbbbbb",
    "..bbbbbb",
    "ffbbbdbb",
    "..bbbbbb",
    "ffbbdbbb",
    "..bbbbbb",
    ".ffbbbbb",
    "f..fbbbb",
    "..f..f.f",
    ".f...f.f",
    "....f...",
    "........",
]), dict(b=0x6A3A6A, f=0x9A5A9A, d=0x4A2A4A))

A["Sea Squirt"] = ([
    "................",
    ".......bb.......",
    "......bddb......",
    "......bbbb..bb..",
    ".....bbbbbbbddb.",
    "....bbbbbbbbbb..",
    "....bllbbbbbb...",
    "...bblbbbbbbb...",
    "...bblbbbbbbb...",
    "...bbbbbbbdbb...",
    "...bbbbbbbbbb...",
    "....bbbbbbbbb...",
    ".....bbbbbbb....",
    "...fffffffffff..",
    "..fffffffffffff.",
    "................",
], dict(b=0x9A7AC8, l=0xD8C8F0, d=0x5A4A8A, f=0x5A5260))

A["Lamprey"] = ([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "..........bbbbt.",
    ".bbb....bbbbbktm",
    "bb.bbbbbbbdddbmm",
    "b....bbbbbbbbbtm",
    "..............t.",
    "................",
    "................",
    "................",
    "................",
], dict(b=0x6A6A5A, d=0x3A3A30))

A["Ray-finned Fish"] = ([
    "................",
    "................",
    "................",
    "................",
    ".......f.f......",
    "......fffff.....",
    "b....bbbbbbbb...",
    "bb.bbdbbdbbbbb..",
    "bbbbbdbbdbbbbkb.",
    "bbbbbdbbdbbbbbbb",
    "bb.bllllllllllm.",
    "b....llllllll...",
    ".......f..f.....",
    "................",
    "................",
    "................",
], dict(b=0xE0B040, d=0x5A6A2A, l=0xF0E0A0, f=0xE08040))

A["Coelacanth"] = ([
    "................",
    "................",
    "................",
    "................",
    "................",
    ".......ff.......",
    "b.....bbbbbb....",
    "bb..bblbbbblbb..",
    ".bbbbbbbblbbbkb.",
    "bbbbbblbbbbbbbbb",
    ".bbbbbbbbblbbbm.",
    "bb..bblbbbbbb...",
    "b.....ff..ff....",
    "......f....f....",
    "................",
    "................",
], dict(b=0x3C5A8A, l=0xDDE6EE, f=0x2E4A6A))

A["Dunkleosteus"] = ([
    "................",
    "................",
    "................",
    "................",
    "................",
    ".........dddd...",
    "b.....bbddlldd..",
    "bb..bbbbdlkldd..",
    ".bbbbbbbddlllddd",
    "bbbbbbbbddddmmtt",
    ".bbbbbbbbddtmmmt",
    "bb..llllllddtt..",
    "b.....f....d....",
    "................",
    "................",
    "................",
], dict(b=0x5A6A7A, d=0x8A8070, l=0xB8B0A0, f=0x46566A))

A["Stingray"] = (mirror([
    "........",
    "......bb",
    ".....bbb",
    "....bbkb",
    "...bbbbb",
    "..bbbbbb",
    ".bbbbdbb",
    "bbbbbbbb",
    ".bbbbbbb",
    "..bbbbdb",
    "...bbbbb",
    "....bbbb",
    "......bb",
    ".......b",
    ".......b",
    "......t.",
]), dict(b=0x8A7A6A, d=0x5A4A40))

A["Megalodon"] = ([
    "................",
    "................",
    "................",
    "........b.......",
    "b......bb.......",
    "bb....bbbb......",
    ".bb.bbbbbbbbbbb.",
    "..bbbbbbbbbbbkbb",
    "..bbbbbbbbdbdbbb",
    "..bbbbbbbbdbdttt",
    "..blllllllldlmmm",
    ".bb.lllllllllttt",
    "bb.....ff..lll..",
    "b.......f.......",
    "................",
    "................",
], dict(b=0x4A5A6A, l=0xB8C0C8, d=0x2E3A48, f=0x3A4A5A))

A["Seahorse"] = ([
    "................",
    "......bb........",
    ".....bbbb.......",
    ".....bbkbbbbb...",
    "......bbb.......",
    ".....bbbl.......",
    "....fbbbll......",
    "...ffbbbll......",
    "....fbbbbl......",
    ".....bbbbl......",
    "......bbbl......",
    ".......bb.......",
    "......bb........",
    "....b.bb........",
    "....bbb.........",
    "................",
], dict(b=0xF0A040, l=0xF8D090, f=0xF8C070))

A["Anglerfish"] = ([
    "................",
    "......ffff......",
    ".....f....f.....",
    "....f......gg...",
    "b...bbbbb..gg...",
    "bb.bbbbbbbb.....",
    ".bbbbbbbbbkbb...",
    "bbbbbbbbbbbbbb..",
    "bbbbbbbbbbtmtmt.",
    ".bbbbbbbbmmmmmm.",
    "bb.bbbbbbtmtmtm.",
    "b...bbbbbbbbbb..",
    ".....bbbbbbb....",
    "................",
    "................",
    "................",
], dict(b=0x4A3A4A, f=0x6A5A6A, g=0xFFF0A0))

A["Tiktaalik"] = ([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "..........bbbb..",
    "b....bbbbbbbkbbb",
    "bb.bbbbbbbbbbbbb",
    ".bbbbdbdbdbbbmmm",
    "b.bbllllllllll..",
    ".....ff....ff...",
    "....f.f...f.f...",
    "................",
    "................",
], dict(b=0x7A8A5A, d=0x4A5A3A, l=0xC8C090, f=0x5A6A3A))

A["Amphibian"] = ([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "..........bbbbb.",
    "b...bbbbbbbbkbbb",
    "bbbbbdbbdbbbbbbb",
    ".bbbbbbbbbbbmmmm",
    "..bllllllllll...",
    "..f.f....f.f....",
    ".ff.f...ff.f....",
    "................",
], dict(b=0x8A6A4A, d=0x5A4030, l=0xC8B080, f=0x6A5038))

A["Salamander"] = ([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "..........bbbb..",
    "bbb..brbbrbbbkbb",
    "..bbbbbbbbbrbbbb",
    "......f.f..f.f..",
    ".....f..f.f..f..",
    "................",
], dict(b=0x2A2A30, r=0xFFC040, f=0x2A2A30))

A["Lizard"] = ([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "............bb..",
    "...........bbkbb",
    "b.....bbbbbbbbb.",
    ".b..bbbdbdbbbl..",
    "..bbbb.f..f.....",
    "......f....f....",
    "................",
], dict(b=0x6AA040, d=0x3A6A2A, l=0xC8D080, f=0x5A8A38))

A["Snake"] = ([
    "................",
    "................",
    "................",
    "...........bbb..",
    "..........bbkbbr",
    "..........bb...r",
    "...........bb...",
    "............bb..",
    "............bb..",
    "...bbbbbbbbbb...",
    "..bbdbdbdbdbb...",
    ".bb..........bb.",
    ".bb..........bb.",
    "..bbdbdbdbdbbb..",
    "...bbbbbbbbbb...",
    "................",
], dict(b=0x8A9A3A, d=0x4A5A28, r=0xE05050))

A["Dinosaur"] = ([
    "................",
    "................",
    "................",
    "......r..r......",
    "....r.rr.rr.....",
    "...rr.rrrrrr....",
    "..rrbbbbbbbbr...",
    "tt.bbbbbbbbbbb..",
    ".tbbbbbbbbbbbbb.",
    "..bbbbbbbbbbbbbb",
    "....bbllllllbbkb",
    "....bb.bb..bb...",
    "....bb.bb..bb...",
    "...bbb.bb.bbb...",
    "................",
    "................",
], dict(b=0x7A8A4A, r=0xC87040, l=0xB8B070))

A["Pterosaur"] = ([
    "................",
    "................",
    "................",
    ".......d........",
    "......ddbbbbbbb.",
    "........bkbbb...",
    "b.......bbb....b",
    "bbb....bbbb..bbb",
    ".bbbbbbbbbbbbbb.",
    "..bbbbbbbbbbbb..",
    "....bbb.lll.....",
    ".........f......",
    "................",
    "................",
    "................",
    "................",
], dict(b=0x9A7A6A, d=0xC85A40, l=0xC8B0A0, f=0x6A5048))

A["Sauropod"] = ([
    "............bb..",
    "...........bbkb.",
    "...........bb...",
    "..........bb....",
    "..........bb....",
    ".........bb.....",
    "....bbbbbbb.....",
    "..bbbbbbbbbb....",
    "bbbbbbbbbbbb....",
    "b..bbbbbbbbb....",
    "...bbllllbbb....",
    "...bb.bb.bb.....",
    "...bb.bb.bb.....",
    "..bbb.bb.bbb....",
    "................",
    "................",
], dict(b=0x9A9070, l=0xC8C8A8))

A["Penguin"] = ([
    "................",
    "......bbb.......",
    ".....bbbbb......",
    ".....bbbkbr.....",
    ".....bbbbbrr....",
    ".....bblll......",
    "....bbbllll.....",
    "...bbbbllll.....",
    "...bbbbllll.....",
    "...bbbbllll.....",
    "....bbbllll.....",
    "....bbbllll.....",
    ".....bblll......",
    "......rr.rr.....",
    "................",
    "................",
], dict(b=0x2A2A3A, l=0xE8EEF0, r=0xFF9A30))

A["Platypus"] = ([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "......bbbbbb....",
    "ddd.bbbbbbbbkb..",
    "dddbbbbbbbbbbrrr",
    "ddd.bllllllbbrr.",
    "....f.f...f.f...",
    "................",
    "................",
], dict(b=0x8A5A3A, l=0xB08A60, d=0x5A3A28, r=0x4A4A50, f=0x5A3A28))

A["Kangaroo"] = ([
    "..........b.b...",
    "..........bbb...",
    "..........bbkb..",
    "..........bbbbb.",
    ".........bbb....",
    "........bbbbf...",
    ".......bbbbl....",
    ".......bbbbl....",
    "......bbbbbl....",
    ".....bbbbbbl....",
    "....bbbbbbbb....",
    "...bb..bbbb.....",
    "..bb....bb......",
    ".bb.....bbbbb...",
    "bb..............",
    "................",
], dict(b=0xC0804A, l=0xE0B080, f=0xA06A3A))

A["Mouse"] = ([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "..........bb....",
    ".........bllb...",
    ".......bbbbbb...",
    ".....bbbbbbbkbb.",
    "....bbbbbbbbbbbm",
    "..b.bbbbbbbbb...",
    ".b...f.f..f.f...",
    "b...............",
    "................",
], dict(b=0x9A9098, l=0xE8A0B0, f=0x7A7078))

A["Bat"] = (mirror([
    "........",
    "........",
    "........",
    "......b.",
    "......bb",
    "f.....kb",
    "ff...fbb",
    "ffffffbb",
    "ffffffbb",
    ".fffffbb",
    ".f.f.fbb",
    "......b.",
    "........",
    "........",
    "........",
    "........",
]), dict(b=0x5A4A4A, f=0x4A3A48))

A["Lemur"] = ([
    "..bdb...........",
    ".d...b..........",
    ".b...d..........",
    "....b....b..b...",
    "....d....bbbb...",
    "....b...llkllk..",
    "....d...bllllm..",
    "....b...bbbbb...",
    "....d..bbbbbb...",
    "....b.bbbbllb...",
    "....dbbbbbllb...",
    "....bbbbbbllb...",
    ".....bbbbbbbb...",
    "......bb..bb....",
    "................",
    "................",
], dict(b=0x9A9098, d=0x2A2A30, l=0xE8E8E0))

A["Ape"] = (mirror([
    "........",
    ".....bbb",
    "....bbbb",
    "....blll",
    "....blkl",
    ".....lll",
    "...bbbbb",
    "..bbbbbb",
    ".bb.bbbb",
    ".b..bbbb",
    "bb..bbbb",
    "b...bbbb",
    "b...bb.b",
    "bb..bb..",
    "....bb..",
    "........",
]), dict(b=0xC8602A, l=0xD8A080))

A["Chimpanzee"] = ([
    "................",
    "................",
    "................",
    "................",
    "..........bbb...",
    ".........bbbbb..",
    ".....bbbbbllkl..",
    "...bbbbbbbblll..",
    "..bbbbbbbbbbml..",
    "..bbbbbbbbbb....",
    "..bbbbbbbbbb....",
    "..bb.b...bb.....",
    "..bb.b...bb.....",
    ".bb..bb..bbb....",
    "................",
    "................",
], dict(b=0x3A3030, l=0xC8A080))

A["Gorilla"] = (mirror([
    "........",
    "........",
    "......bb",
    ".....bbb",
    ".....bdd",
    "....bbkd",
    "..bbbbdd",
    ".bbbbbbb",
    "bbbbbbbb",
    "bbb.bbll",
    "bb..bbll",
    "bb..bbbb",
    "bb..bb.b",
    "bbb.bb..",
    "....bbb.",
    "........",
]), dict(b=0x2A2A30, d=0x4A4A50, l=0x6A6A70))

A["Rabbit"] = ([
    ".........b.b....",
    ".........b.b....",
    ".........bbb....",
    "........bbbbb...",
    "........bbbkbb..",
    "........bbbbbbm.",
    ".....bbbbbbbb...",
    "...bbbbbbbbb....",
    "..bbbbbbbbbb....",
    ".lbbbbbbbbbl....",
    ".lbbbbbbbbbl....",
    "..bbbbbbbbbl....",
    "...bbb..bbbbb...",
    "................",
    "................",
    "................",
], dict(b=0xC0A080, l=0xF0E8E0))

A["Horse"] = ([
    "................",
    "............b...",
    "...........bbb..",
    "..........dbkbb.",
    ".........ddbbbbb",
    "........ddbb..bm",
    "........dbb.....",
    "..bbbbbbbbb.....",
    "dbbbbbbbbbb.....",
    "d.bbbbbbbbb.....",
    "d.bbllllbbb.....",
    "..bb....bb......",
    "..b.b...b.b.....",
    "..b.b...b.b.....",
    ".dd.dd.dd.dd....",
    "................",
], dict(b=0x8A5A3A, d=0x2A2020, l=0xB08060))

A["Dolphin"] = ([
    "................",
    "................",
    "................",
    "................",
    "................",
    ".......b........",
    "......bb........",
    "b...bbbbbbbbbb..",
    "bbbbbbbbbbbbbkbb",
    ".bbbllllllllbbbb",
    "bb...lllllll..mm",
    "b........f......",
    "................",
    "................",
    "................",
    "................",
], dict(b=0x7A8A9A, l=0xC8D0D8, f=0x5A6A7A))

A["Lion"] = ([
    "................",
    "................",
    "................",
    "..........dddd..",
    ".........ddbbdd.",
    ".........dbbkbbd",
    ".........dbbbbbb",
    "dd.......dbbbbm.",
    ".d..bbbbbbdddd..",
    "..bbbbbbbbbbbd..",
    "..bbbbbbbbbbb...",
    "..bbllllllbbb...",
    "..bb.......bb...",
    "..b.b.....b.b...",
    ".bb.bb...bb.bb..",
    "................",
], dict(b=0xD8A050, d=0x8A4A20, l=0xE8C890))

# --- boon icons ---------------------------------------------------------------

# a glowing angler lure
A["Boon Lure"] = ([
    "................",
    "..........ggg...",
    ".......l.gglgg..",
    ".........gwllg..",
    ".........glllg..",
    "........lgglgg.l",
    ".........fggg...",
    "........f.......",
    ".......ff.......",
    ".......f.....l..",
    "......f.........",
    ".....ff.........",
    ".....f..........",
    ".....f..........",
    "....ff..........",
    "....f...........",
], dict(f=0x6A5A6A, g=0xFFC84A, l=0xFFF0A0))

# a magnifying glass
A["Boon Lens"] = ([
    "................",
    "...bbbbbb.......",
    "..bbllllbb......",
    ".bblwllllbb.....",
    ".blwwlllllb.....",
    ".blwllllllb.....",
    ".bllllllllb.....",
    ".bllllllllb.....",
    ".bbllllllbb.....",
    "..bbllllbb......",
    "...bbbbbb.dd....",
    "..........ddd...",
    "...........ddd..",
    "............ddd.",
    ".............ddd",
    "..............dd",
], dict(b=0xD8A860, l=0x9FD8E0, d=0x6A4A30))

# a sparking flask
A["Boon Catalyst"] = ([
    "............g...",
    "....gbbbbbb.....",
    "......b..b......",
    "......b..b......",
    "...g..b..b..g...",
    "......b..b......",
    "......bbbb......",
    ".....bb..bb.....",
    "....b.b..b.b....",
    "...bbllllllbb...",
    "...bllllllglb...",
    "...blllgllllb...",
    "...bbllllglbb...",
    "....blgllllb....",
    ".....bbllbb.....",
    "......bbbb......",
], dict(b=0xB8C8D8, l=0xB070E0, g=0xF0D0FF))

# a four-leaf clover
A["Boon Charm"] = ([
    "................",
    "................",
    "...bbbb..bbbb...",
    "..bbbbbbbbbbbb..",
    "..bblbbbbblbbb..",
    "..bbbbbbbbbbbb..",
    "..bbbbbbbbbbbb..",
    "...bbbbbbbbbb...",
    "..bbbbbbbbbbbb..",
    "..bblbbbfblbbb..",
    "..bbbbbbfbbbbb..",
    "..bbbbbbbfbbbb..",
    "...bbbb..fbbb...",
    ".........f......",
    "..........f.....",
    "..........f.....",
], dict(b=0x5CB84A, l=0x9FE0A0, f=0x3A6A2A))

# a stopwatch with speed lines
A["Boon Tailwind"] = ([
    "................",
    "................",
    ".........bbb....",
    ".........bbb....",
    ".......bbbbbb...",
    "......bllllllb..",
    "ffff.blllldlllb.",
    ".....blllldlllb.",
    ".....blllldlllb.",
    ".ffffbllllddllb.",
    ".....blllllddlb.",
    ".....bllllllllb.",
    "ffff..bllllllb..",
    ".......bbbbbb...",
    "................",
    "................",
], dict(b=0x9FE8E0, l=0xE8EEF0, d=0x2A3A48, f=0x9FE8E0))

# an erupting volcano
A["Boon Tectonics"] = ([
    "...........ssss.",
    "........o.sssss.",
    ".....o.....ss...",
    ".......o........",
    "..........o.....",
    "......rrrr......",
    "......rrrr......",
    "......bbrrr.....",
    "......brbbr.....",
    ".....bbrbbr.....",
    "....bbbrbbrr....",
    "...bbbrbbbbrb...",
    "...bbbrbbbbbb...",
    "..bbbbbbbbbbbb..",
    ".bbbbbbbbbbbbbb.",
    "................",
], dict(b=0x5A4A48, r=0xFF6A28, o=0xFFB040, s=0x9A9098))


# === The 151 expansion ===

A["Nautilus"] = ([
    "................",
    "................",
    ".....bbbbb......",
    "...bbdbbdbbb....",
    "..bdbbdbbdbbb...",
    ".bbllllllbdbbb..",
    ".bllddddllbdbb..",
    "bbldbbbbdlbbdbb.",
    "bbldbwbbdlbbbkbb",
    "bbldbbbbdlbbbbff",
    ".bllddddllbbffff",
    ".bbllllllbbf.f.f",
    "..bbbbbbbbf.f.f.",
    "....bbbbb.......",
    "................",
    "................",
], dict(b=0xECD696, d=0xC0503A, l=0xF4F1E8, f=0xE0A878))

A["Fly"] = (mirror([
    "........",
    "........",
    ".....rr.",
    ".....rrb",
    "......bb",
    ".llll.bb",
    "llllllbb",
    "lllllldb",
    ".lllllbb",
    "..lll.db",
    "......bb",
    ".....f.d",
    "....f..b",
    "...f....",
    "........",
    "........",
]), dict(b=0x3E3848, d=0x1C1A22, l=0xB8CAD6, r=0xC83E1C, f=0x2A2632))

A["Clownfish"] = ([
    "................",
    "................",
    "................",
    "................",
    ".......d........",
    "......dbd.......",
    "....dbbldbbd....",
    "d..dbbbldbbbbd..",
    "dddbbbbldbbbkbd.",
    "dldbbbbldbbbbbld",
    "dddbbbbldbbbbbd.",
    "d..dbbbldbbbbd..",
    "....dbbldbbd....",
    ".......d........",
    "................",
    "................",
], dict(b=0xFF6A28, l=0xF4F1E8, d=0x1C1A22))

A["Lungfish"] = ([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "...........bbb..",
    ".bbbbbbbbbbbbkbb",
    "bbbdbbdbbdbbbbbm",
    ".blllllllllllbb.",
    "....f.....f.....",
    "...f.....f......",
    "................",
    "................",
    "................",
], dict(b=0x6A7A4A, d=0x4F5F38, l=0xC8A260, f=0x4F5F38))

A["Pig"] = ([
    "................",
    "................",
    "................",
    "................",
    "................",
    "...........dd...",
    "....bbbbbbbbbd..",
    "r..bbbbbbbbbbkb.",
    ".rbbbbbbbbbbbbrr",
    "r.bbbbbbbbbbbbrd",
    "..bbllllllllbbb.",
    "...bbbbbbbbbbb..",
    "...ff.ff..ff.ff.",
    "...dd.dd..dd.dd.",
    "................",
    "................",
], dict(b=0xE48CA0, l=0xE0A878, d=0xBA6080, r=0xE48CA0, f=0xE48CA0))

A["Tuatara"] = ([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "......r.r.r.r.r.",
    ".....bbbbbbbbbbb",
    "b..bbbdbbdbbbkbb",
    ".bbbbbbbbbbbbbb.",
    "..b.llllllll....",
    "....f.f...f.f...",
    "...f...f.f...f..",
    "................",
    "................",
], dict(b=0x6A7A4A, d=0x4F5F38, r=0xECD696, l=0xC8A260, f=0x4F5F38))

A["Sea Turtle"] = (mirror([
    "........",
    "......bb",
    ".....kbb",
    "......bb",
    ".ff..ddd",
    "fff.dddd",
    "ffddlddl",
    ".fdllddl",
    "..dldlld",
    "..dllddl",
    "..ddlddl",
    "...ddddd",
    "...f.ddd",
    "..ff....",
    "........",
    "........",
]), dict(b=0x6A7A4A, f=0x6A7A4A, d=0x604630, l=0xA07C46))

A["Plesiosaur"] = ([
    "................",
    "................",
    "............bbb.",
    "...........bbkbb",
    "...........bb...",
    "..........bb....",
    ".........bb.....",
    "........bb......",
    "...bbbbbbb......",
    ".bbbbbbbbbb.....",
    "bbllllllllb.....",
    "..ff....ff......",
    ".ff......ff.....",
    "................",
    "................",
    "................",
], dict(b=0x567AAA, l=0xB8CAD6, f=0x304670))

A["Ichthyosaur"] = ([
    "................",
    "................",
    "................",
    "................",
    "................",
    "b.......d.......",
    "bb.....dd.......",
    ".bbbbbbbbbbbb...",
    "..bbbbbbbbbbekb.",
    "..bllllllllbbbbb",
    ".bb.lllllll.....",
    "bb....f....f....",
    "b....f....f.....",
    "................",
    "................",
    "................",
], dict(b=0x567AAA, d=0x304670, l=0xDFEEF6, f=0x304670))

A["Triceratops"] = ([
    "................",
    "................",
    "................",
    "..........dd....",
    ".........dbbd...",
    "........dbbbbt..",
    "........dbbekbtt",
    "...bbbbbdbbbbbt.",
    ".bbbbbbbbdbbbbbb",
    "bbbbbbbbbbdbbbm.",
    ".bbbbbbbbbbbbt..",
    "..bbllllllbbb...",
    "..ff.ff..ff.ff..",
    "..ff.ff..ff.ff..",
    "................",
    "................",
], dict(b=0xA07C46, d=0x6E4836, l=0xCEAA6E, f=0x8C5C34))

A["Velociraptor"] = ([
    "................",
    "................",
    "............bbb.",
    "...........bbkbb",
    "...........bbmm.",
    "..........bbb...",
    "rr.....bbbbbf...",
    ".rrbbbbbbbbf.f..",
    "...bbbbbbbb.....",
    "....lllbbb......",
    ".....bb.bb......",
    ".....b...b......",
    "....tb...bt.....",
    "................",
    "................",
    "................",
], dict(b=0x965C3E, r=0x604630, l=0xC89070, f=0x604630))

A["Archaeopteryx"] = ([
    "................",
    "................",
    "................",
    "...........bbb..",
    "..........bbkbt.",
    "..........bbbb..",
    "......dddbbbb...",
    ".....ddddbbbl...",
    "rrrrrbbbbbbll...",
    "r.r.rbbbbbll....",
    "......dd.f......",
    ".....dd..f......",
    "....d...ff......",
    "................",
    "................",
    "................",
], dict(b=0x965C3E, d=0x3E3848, r=0x604630, l=0xC89070, f=0x3E3848))

A["Ostrich"] = ([
    "..........bb....",
    "..........bkr...",
    "..........b.....",
    "..........b.....",
    "..........b.....",
    ".........bb.....",
    "....dddddb......",
    "..lddddddd......",
    ".lldddddddd.....",
    "..dddddddd......",
    "......f.f.......",
    "......f.f.......",
    "......f..f......",
    ".....f...f......",
    ".....ff..ff.....",
    "................",
], dict(b=0xE0A878, d=0x2A2632, l=0xF4F1E8, f=0xE0A878, r=0xE0A878))

A["Parrot"] = ([
    "................",
    "................",
    "..........bbb...",
    ".........bbekt..",
    ".........bbbbtt.",
    "........bbbb.t..",
    ".......bbbbb....",
    "......bgggbb....",
    ".....bggrrbb....",
    "....ggrrrbbb....",
    "...grrr.bbb.....",
    "..rr.....ff.....",
    ".rr..dddddddd...",
    "................",
    "................",
    "................",
], dict(b=0xC83E1C, g=0xFFBE5A, r=0x567AAA, f=0x3E3848, d=0x8C5C34))

A["Owl"] = (mirror([
    "........",
    "..b.....",
    "..bb....",
    "..bbbbbb",
    ".bllllll",
    ".bleekll",
    ".bekkkel",
    ".bleekll",
    ".bbllllr",
    ".bdbdbbb",
    ".bbdbdbb",
    ".bdbdbdb",
    "..bbbbbb",
    "....f.f.",
    "...ffff.",
    "........",
]), dict(b=0xA07C46, l=0xECD696, d=0x604630, r=0xFFBE5A, f=0xFFBE5A))

A["Koala"] = (mirror([
    "........",
    ".bb.....",
    "bllb....",
    "bllbbbbb",
    ".bbbbbbb",
    "..bbbbbb",
    "..bbkbbb",
    "..bbbbdd",
    "..bbbbdd",
    "...bbbbd",
    "..lbbbbb",
    ".llbbbbb",
    ".lbbbbbb",
    "..bbbbbb",
    "..ff..ff",
    "........",
]), dict(b=0x8CA0B2, l=0xDFEEF6, d=0x1C1A22, f=0x5A6678))

A["Sloth"] = ([
    "................",
    "gggggggggggggggg",
    "..tt.......tt...",
    "...f.......f....",
    "...f.......f....",
    "...bbbbbbbbbb...",
    "..bbbbbbbbbbbb..",
    "..bbbbbbbbllbb..",
    "..bbbbbbblekb...",
    "...bbbbbbllbb...",
    "....bbbbbbb.....",
    "................",
    "................",
    "................",
    "................",
    "................",
], dict(b=0x96704A, l=0xECD696, g=0x604630, f=0x96704A))

A["Giraffe"] = ([
    ".........d.d....",
    ".........bbbb...",
    "........bbbkbb..",
    "........bb..bm..",
    "........bd......",
    "........bb......",
    ".......bdb......",
    ".......bb.......",
    ".bbbbbbbdb......",
    "bbdbbdbbbb......",
    ".bbbdbbdbb......",
    ".bdbbbbdb.......",
    ".f.f...f.f......",
    ".f.f...f.f......",
    ".f.f...f.f......",
    "................",
], dict(b=0xCEAA6E, d=0x8C5C34, f=0xCEAA6E))

A["Hippo"] = ([
    "................",
    "................",
    "................",
    "................",
    "................",
    "...........bb...",
    "...bbbbbbbbbkbb.",
    ".bbbbbbbbbbbbbbb",
    "bbbbbbbbbbbbbbbb",
    "bbbbbbbbbbbbbmtb",
    "bbllllllllbbbbbb",
    ".bbbbbbbbbbb....",
    ".ff.ff...ff.ff..",
    "................",
    "................",
    "................",
], dict(b=0x7A6A7E, l=0xE48CA0, f=0x5A5260))

A["Rhino"] = ([
    "................",
    "................",
    "................",
    "................",
    "...........b..t.",
    "..........bb.tt.",
    "...bbbbbbbbbkbtt",
    ".bbbbbbbbbbbbbbb",
    "bbbdbbbbbbbbbbb.",
    "bbbbbbbbbbbbbbm.",
    ".bbbllllllbbb...",
    ".ff.ff...ff.ff..",
    ".ff.ff...ff.ff..",
    "................",
    "................",
    "................",
], dict(b=0x8CA0B2, d=0x5A6678, l=0xB8CAD6, f=0x5A6678))

A["Bear"] = ([
    "................",
    "................",
    "................",
    "................",
    "...........bb...",
    ".....bbbbbbbbb..",
    "...bbbbbbbbbkbb.",
    "..bbbbbbbbbbbbbd",
    ".bbbbbbbbbbbbbb.",
    ".bbbbbbbbbbbb...",
    ".bbbllllbbbbb...",
    ".bff.ff..ff.ff..",
    "..ff.ff..ff.ff..",
    "................",
    "................",
    "................",
], dict(b=0x8C5C34, l=0xA07C46, d=0x1C1A22, f=0x604630))

A["Seal"] = ([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "............bb..",
    "...........bbkb.",
    "..........bbbbbm",
    "....bbbbbbbbbb..",
    "..bbbbbbbbbbbb..",
    "fbbllllllllbb...",
    "ff.......ff.....",
    "gggggggggggggggg",
    "................",
    "................",
], dict(b=0x8CA0B2, l=0xDFEEF6, f=0x5A6678, g=0xE6F0F6))

A["Dog"] = ([
    "................",
    "................",
    "................",
    "..........bb....",
    ".........bbbb...",
    ".........bbkbbd.",
    ".........dbbbb..",
    "b........dlbm...",
    ".b...bbbbbbl....",
    "..bbbbbbbbbl....",
    "...bbdddbbbl....",
    "...bllllbbb.....",
    "...bb....bb.....",
    "...bb....bb.....",
    "...ll....ll.....",
    "................",
], dict(b=0xCEAA6E, d=0x8C5C34, l=0xF4F1E8))

A["Tiger"] = ([
    "................",
    "................",
    "................",
    "..........bb.b..",
    "..........bbbb..",
    ".........bbbkbb.",
    ".........lbbbbbb",
    "d........lllbbm.",
    ".d..bbdbbdbbbb..",
    "..bbbbdbbdbbdb..",
    "..bdbbdbbdbbb...",
    "..bbllllllbbb...",
    "..bb.......bb...",
    "..b.b.....b.b...",
    ".bb.bb...bb.bb..",
    "................",
], dict(b=0xFF6A28, d=0x1C1A22, l=0xF4F1E8))

A["Cat"] = ([
    "................",
    "................",
    "...........b.b..",
    "..........bbbbb.",
    "..........bbkbbb",
    "..........bbbbm.",
    "...........bbb..",
    "..b.......bbbb..",
    ".b.......bbbbb..",
    ".b......bbbbbb..",
    ".b.....bbbbbbb..",
    "..b...bbbbllbb..",
    "...bbbbbbbllbb..",
    ".....bbbbbbbbb..",
    "......ll...ll...",
    "................",
], dict(b=0x3E3848, l=0xF4F1E8))

A["Sabre-tooth"] = ([
    "................",
    "................",
    "................",
    "..........bb.b..",
    ".........bbbbb..",
    ".........bbkbbb.",
    ".........bbbbbbb",
    "..b......lbbbbb.",
    "..bbbbbbbbbbt.t.",
    ".bbbbbbbbbbbt.t.",
    ".bbbbbbbbbbb....",
    "..bbllllllbb....",
    "..bb......bb....",
    "..bb......bb....",
    ".bbb.....bbb....",
    "................",
], dict(b=0xC8A260, l=0xECD696))

A["Giant Panda"] = (mirror([
    "........",
    ".dd.....",
    "ddddbbbb",
    "ddbbbbbb",
    ".bbbbbbb",
    ".bbddbbb",
    ".bdwdbbb",
    ".bddbbbb",
    "..bbbbbd",
    "...bbbbm",
    "..dddbbb",
    ".ddddbbb",
    ".dddbbbb",
    "..bbbbbb",
    "..dd..dd",
    "........",
]), dict(b=0xF4F1E8, d=0x1C1A22))

A["Cow"] = ([
    "................",
    "................",
    "................",
    "............t...",
    "...........dbt..",
    "..........dbkbb.",
    "..bbddbbbbbbbbll",
    "d.bddddbbbdbbbll",
    "d.bbddbbbddbb...",
    ".dbbbbbbbbbbb...",
    "..bbbbbbrrbbb...",
    "..bb.....rbb....",
    "..bb......bb....",
    "..dd......dd....",
    "................",
    "................",
], dict(b=0xF4F1E8, d=0x1C1A22, l=0xE48CA0, r=0xE48CA0))

A["Chicken"] = ([
    "................",
    "................",
    "...........rr...",
    "..........rbbr..",
    "..........bbkbg.",
    "..........bbbgg.",
    "...b......bbbr..",
    "..bbb....bbbb...",
    "..bbbbbbbbbbb...",
    "...bbbbbbbbbb...",
    "....bbbbbbbb....",
    ".....bbbbbb.....",
    "......g..g......",
    ".....gg.gg......",
    "................",
    "................",
], dict(b=0xECD696, r=0xC83E1C, g=0xFFB048))

A["Songbird"] = ([
    "................",
    "................",
    "................",
    "................",
    "................",
    "..........bbb...",
    ".........bbkbd..",
    ".........bbbb...",
    "......bbbbllb...",
    "....bbbbbllll...",
    "..bbbbbbllll....",
    "bbb..bbblll.....",
    ".......ff.......",
    "...gggggggggg...",
    "................",
    "................",
], dict(b=0x8C5C34, l=0xFF6A28, d=0x3E3848, f=0x3E3848, g=0x604630))

A["Dodo"] = ([
    "................",
    "................",
    "..........bbb...",
    ".........bbkbgg.",
    ".........bbbgggg",
    ".........bbb..gg",
    "........bbb.....",
    "...l..bbbbb.....",
    "..lllbbbbbbb....",
    "...lbbbbbbbbb...",
    "....bbbbbbbbb...",
    ".....bbbbbbb....",
    "......ff.ff.....",
    ".....fff.fff....",
    "................",
    "................",
], dict(b=0x8CA0B2, g=0xECD696, l=0xF4F1E8, f=0xFFB048))

A["True Bug"] = (mirror([
    "....f...",
    ".....f..",
    "......bb",
    ".....bbb",
    "..ddbbbb",
    ".fdbbbbb",
    "f.dbbbbl",
    "..dbbbll",
    ".fdbblll",
    "f.dbbbll",
    "..ddbbbl",
    ".f.ddbbb",
    "f...ddbb",
    "......dd",
    "........",
    "........",
]), dict(b=0x4F8A3A, l=0x8FC878, d=0x205A1E, f=0x2A2632))

A["Wasp"] = ([
    "................",
    "................",
    "................",
    "..........r.....",
    ".......ll..r....",
    "......llll.bb...",
    "......lll.bbkb..",
    ".gdgdg..bbbbb...",
    "dgdgdgd.bbb.....",
    ".gdgdgdbb.......",
    "..gdgd..f.f.....",
    "........f..f....",
    "................",
    "................",
    "................",
    "................",
], dict(g=0xFFBE5A, d=0x1C1A22, b=0x3E3848, l=0xB8CAD6, r=0x1C1A22, f=0x1C1A22))

A["Mite"] = (mirror([
    "........",
    "........",
    "........",
    "........",
    ".f....bb",
    "..f.bkbb",
    "f.fbbbbb",
    ".fbbbbbb",
    "f.bbbbbb",
    ".fbbbbbb",
    "f.fbbbbb",
    "..f.bbbb",
    ".f....bb",
    "........",
    "........",
    "........",
]), dict(b=0xC83E1C, f=0x962818))

A["Termite"] = ([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "..............r.",
    "............bbr.",
    "..lllllllll.bbbm",
    ".lllllllllllbbbb",
    "..lllllllll.bb..",
    "...f.f.f.f.f....",
    "................",
    "................",
    "................",
], dict(l=0xECD696, b=0xA07C46, r=0x8C5C34, f=0xC89070))

A["Moss Animal"] = ([
    "................",
    "..r....r....r...",
    ".r.r..r.r..r.r..",
    "..b....b....b...",
    "..b..r.b.r..b...",
    "..bb.rrbrr.bb...",
    "...bb.bbb.bb....",
    "....bbbbbbb.....",
    "..r..bbbbb..r...",
    ".r.r.bbbbb.r.r..",
    "..bb.bbbbb.bb...",
    "...bbbbbbbbb....",
    ".....bbbbb......",
    "......bbb.......",
    "....ggggggg.....",
    "................",
], dict(b=0xECD696, r=0xE48CA0, g=0x5A5260))

A["Brittle Star"] = (mirror([
    ".......b",
    ".......b",
    "......bb",
    ".......b",
    "b......b",
    ".bb...bd",
    "...bbbdd",
    ".....ddd",
    "....bbdd",
    "...b..bb",
    "..b.....",
    "..bb....",
    "...b....",
    "..b.....",
    ".bb.....",
    "........",
]), dict(b=0xE0A878, d=0xC0503A))

A["Carp"] = ([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "........bb......",
    "......bbbbb.....",
    "d...bbdbdbbbb...",
    "dd.bbbbbbbbbkbb.",
    ".dbbdbdbdbbbbbbm",
    "dd.bllllllllbbf.",
    "d...bbbbbbbb..f.",
    "......f..f......",
    "................",
    "................",
], dict(b=0xCEAA6E, d=0x8C5C34, l=0xECD696, f=0xC89070))

A["Dickinsonia"] = (mirror([
    "........",
    "......bl",
    "....bbbl",
    "...ddddl",
    "..bbbbbl",
    "..dddddl",
    ".bbbbbbl",
    ".ddddddl",
    ".bbbbbbl",
    ".ddddddl",
    "..bbbbbl",
    "..dddddl",
    "...bbbbl",
    "....dddl",
    "......bl",
    "........",
]), dict(b=0xC89070, d=0x965C3E, l=0xECD696))

A["Dimetrodon"] = ([
    "................",
    ".....d.d.d......",
    "....dldldld.....",
    "....lllllll.....",
    "...llllllll.....",
    "...lllllllll....",
    "....bbbbbbbbbb..",
    "b.bbbbbbbbbbkbb.",
    ".bbbbbbbbbbbbbbm",
    "..bb.llllll.bb..",
    "..f.f......f.f..",
    ".f...f....f...f.",
    "................",
    "................",
    "................",
    "................",
], dict(l=0xDC6E54, d=0x8A3A30, b=0x965C3E, f=0x6E4836))

A["Lucy"] = (mirror([
    "........",
    "........",
    "........",
    "......bb",
    ".....bbb",
    ".....lkl",
    ".....lll",
    "......bb",
    "....bbbb",
    "...bbbbb",
    "...b.bbb",
    "...b.bbb",
    "..b..bbb",
    ".....bb.",
    "....bbb.",
    "........",
]), dict(b=0x8C5C34, l=0xC89070))

A["Neanderthal"] = (mirror([
    "........",
    "......dd",
    ".....ddd",
    ".....ddd",
    ".....ddd",
    ".....bkb",
    ".....bbb",
    "....rrrr",
    "...rrrrr",
    "..brrrrr",
    "..b.rrrr",
    "..b..bbb",
    ".....bb.",
    ".....bb.",
    "....bbb.",
    "........",
]), dict(b=0xC8906E, d=0x4A2E20, r=0x96704A))


A["Pakicetus"] = ([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "..........bbb...",
    ".........bbkbbb.",
    "b........bbbbbbm",
    ".b...bbbbbbb....",
    "..bbbbbbbbbb....",
    "...bbllllbbb....",
    "...bb....bb.....",
    "...b.b...b.b....",
    "..bb.bb.bb.bb...",
    "................",
], dict(b=0x96704A, l=0xC89070))

A["Acanthostega"] = ([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "..........bbb...",
    ".......bbbbbkbb.",
    "g..bbbbbbbbbbbbm",
    "ggbbbdbbdbbbbbb.",
    "g.bllllllllll...",
    "....ff.....ff...",
    "...f.f.....f.f..",
    "................",
    "................",
], dict(b=0x6A7A4A, d=0x4F5F38, l=0xC8A260, g=0x4F8A80, f=0x4F5F38))


def check():
    for name, (rows, pal) in A.items():
        assert len(rows) == GRID, (name, len(rows))
        for i, r in enumerate(rows):
            assert len(r) == GRID, (name, i, len(r), r)
            for c in r:
                assert c == '.' or c in pal or c in FIXED, (name, c)
